name: Validation

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with: 
          root: pages/

